// Opportunity dataset for PluginPilot discovery scoring.
// Factor scores are 1-5 (5 = best for us). comp: 5 = little competition. mvp: 5 = simplest.
// native: 5 = plain ChatGPT clearly cannot do it (plugin has a hard advantage).
// risk: 0-100 (legal, privacy, platform, absorption risk combined).
// Scores are analyst judgements informed by docs/MARKET_RESEARCH.md; they are hypotheses, not data.

export const WEIGHTS = {
  pain: 20, freq: 12, fit: 10, native: 13, mcp: 8, wtp: 10, comp: 10, mvp: 7, ret: 5, dist: 5,
};

// [id, name, targetUser, problem, currentWorkaround, examplePrompt, pluginEdge, alternatives, monetization, mvpDays,
//  pain, freq, fit, native, mcp, wtp, comp, mvp, ret, dist, risk]
export const ROWS = [
  ['nk-check', 'Nebenkosten-Check (DE utility-bill audit)', 'German tenants (~21M rental households)', 'Annual service-charge statement is wrong in ~1 of 2 cases; tenants cannot check legality, deadlines, CO2 split, benchmarks', 'Ignore it, Mieterverein membership, Mineko (49-89 EUR), ask ChatGPT loosely', 'Hier ist meine Nebenkostenabrechnung, ist die korrekt?', 'Deterministic BetrKV/§556 BGB/HeizkostenV/CO2KostAufG rule engine + Betriebskostenspiegel benchmarks + objection letter', 'Mineko, Mieterverein, lawyers, generic ChatGPT', 'Free check, paid letter/report 9-19 EUR per use', 5, 5, 2, 5, 4, 4, 2, 1, 4, 2, 5, 35],
  ['nk-landlord', 'Nebenkostenabrechnung erstellen (small landlords)', 'Private landlords with 1-10 units', 'Building a legally correct annual statement with allocation keys is error-prone', 'Excel templates, Haufe/ImmoScout tools', 'Erstelle die Nebenkostenabrechnung für meine 3 Mieter', 'Allocation math + legal template + PDF output', 'objego, Vermietet.de, Excel templates', 'Per statement 15-29 EUR or subscription', 7, 4, 2, 5, 4, 4, 4, 3, 3, 3, 4, 30],
  ['erech-inbox', 'E-Rechnung lesen & prüfen (DE SMB inbox)', 'German SMBs/freelancers receiving XRechnung/ZUGFeRD', 'Mandatory receipt since 2025; XML is unreadable; invalid invoices risk input-VAT deduction', 'Free web viewers, accounting software', 'Ich habe eine XRechnung bekommen, was steht drin und ist sie gültig?', 'EN16931/KoSIT validation, §14 UStG checks, VIES lookup, readable summary', 'Rechnungslotse MCP (18 tools), InvoiceXML MCP, web viewers, lexoffice/sevdesk', 'Freemium, 5-9 EUR/mo', 4, 3, 4, 4, 5, 5, 3, 2, 3, 3, 3, 15],
  ['erech-create', 'E-Rechnung erstellen from chat', 'German freelancers issuing B2B invoices (2027/28 mandate)', 'Must issue XRechnung/ZUGFeRD; Word/Excel cannot', 'lexoffice, sevdesk, kostenlose-erechnung.de', 'Mach mir eine ZUGFeRD-Rechnung für Kunde X über 1.200 EUR', 'Valid structured output format + PDF/A-3', 'Scribo (free MCP), Rechnungslotse, InvoiceXML, accounting suites', 'Freemium per invoice', 5, 4, 4, 4, 5, 5, 3, 2, 3, 4, 3, 20],
  ['vat-xborder', 'EU cross-border VAT treatment checker', 'EU freelancers/SMBs invoicing other EU countries', 'Reverse charge vs OSS vs local VAT; wrong invoice wording; VIES proof', 'Ask accountant, Google, VIES site', 'Muss ich einem Kunden in Österreich Umsatzsteuer berechnen?', 'Live VIES check + rule engine + required invoice wording + audit record', 'vatnode MCP, VIES Smoother, accountants', 'Freemium, 5-10 EUR/mo', 4, 4, 3, 5, 4, 4, 4, 2, 4, 3, 3, 30],
  ['tender-find', 'Public tender finder (TED/national)', 'SMBs bidding on public contracts', 'Finding relevant tenders across portals daily', 'Alert services, manual portal checks', 'Find open IT tenders in Bavaria above 100k', 'Live TED API search, CPV/NUTS mapping', 'Tenqual (in ChatGPT dir), LexSocket, TenderAPI, DTAD, Vergabepilot', 'Subscription 29-99 EUR/mo', 7, 4, 4, 4, 5, 5, 4, 2, 3, 5, 3, 15],
  ['tender-req', 'Tender requirements matrix extractor', 'Bid managers', 'Turning 100-page RFPs into compliance matrices', 'Manual Excel matrix', 'Extract all must-requirements from this RFP into a matrix', 'Structured extraction + XLSX', 'Native ChatGPT does much of it; Loopio, Responsive', 'Per document', 4, 4, 3, 4, 2, 3, 4, 3, 4, 3, 3, 30],
  ['gaeb', 'GAEB/LV file reader & pricer', 'German trades/contractors', 'GAEB X83/X84 bill of quantities files need special software', 'Expensive AVA software, manual retyping', 'Öffne diese GAEB-Datei und mach ein Angebot', 'Parsing proprietary format + pricing calc + export X84', 'AVA tools (California, ORCA), GAEB viewers', 'Per file or 19 EUR/mo', 7, 4, 4, 3, 5, 4, 4, 4, 2, 4, 3, 20],
  ['trade-quote', 'Trade quote builder (Handwerker Angebot)', 'Small trade businesses', 'Quotes take hours in Excel/Word', 'Excel, Tradify, Hero', 'Erstell ein Angebot für 40m² Fliesen inkl. Material', 'Price database + PDF output', 'Hero, Tradify, ToolTime, native ChatGPT', 'Subscription', 6, 4, 4, 4, 2, 3, 4, 2, 3, 4, 3, 25],
  ['shipping-rates', 'Parcel rate comparer (DE/EU)', 'Small e-commerce sellers', 'Comparing DHL/DPD/GLS/Hermes rates per parcel', 'Carrier sites, Sendcloud', 'Cheapest way to ship a 4kg parcel to Austria?', 'Live/maintained rate tables', 'Sendcloud, Shipcloud, Packlink', 'Affiliate/lead gen', 3, 3, 4, 4, 4, 4, 2, 2, 4, 3, 3, 20],
  ['customs-hs', 'HS/customs tariff code finder', 'Exporters, Etsy sellers', 'Wrong HS codes cause delays/duty errors', 'TARIC lookup, broker', 'What HS code is a ceramic coffee mug?', 'Official TARIC data + duty rates', 'Zonos, TARIC, native guesses', 'Per lookup credits', 4, 4, 3, 4, 4, 5, 3, 3, 3, 3, 3, 35],
  ['bank-recon', 'Bank CSV vs invoices reconciliation', 'Small businesses, bookkeepers', 'Matching bank lines to invoices monthly', 'Excel, accounting software', 'Match this bank export against my open invoices', 'Deterministic fuzzy matching', 'Native ChatGPT data analysis, accounting suites', 'Freemium', 3, 4, 4, 3, 2, 3, 3, 2, 4, 4, 3, 35],
  ['receipt-datev', 'Receipts to DATEV export', 'Freelancers with Steuerberater', 'Monthly receipt handover', 'Shoebox, scanning apps', 'Turn these receipts into a DATEV CSV for my accountant', 'DATEV format + SKR03/04 mapping', 'Candis, GetMyInvoices, lexoffice', 'Subscription', 5, 4, 4, 3, 3, 3, 4, 2, 3, 4, 3, 35],
  ['payslip', 'Gehaltsabrechnung erklären/prüfen', 'German employees', 'Payslips are opaque; errors in tax class etc.', 'Ask HR, Google', 'Ist meine Gehaltsabrechnung richtig?', 'Official Lohnsteuer calc (BMF algorithm)', 'Brutto-Netto-Rechner sites, native ChatGPT', 'Free/lead gen', 4, 3, 2, 5, 4, 4, 2, 3, 3, 2, 4, 40],
  ['brutto-netto', 'Brutto-Netto & offer comparison', 'German job seekers', 'Comparing job offers net', 'Online calculators', 'Was bleibt netto von 65k in Steuerklasse 1 in Köln?', 'BMF PAP algorithm exact', 'Many free calculators', 'Lead gen only', 3, 2, 3, 5, 4, 4, 1, 2, 4, 2, 3, 20],
  ['steuer-pendler', 'Steuererklärung deduction finder', 'German employees', 'Missing deductions (Pendlerpauschale, Homeoffice)', 'WISO, Taxfix', 'Was kann ich von der Steuer absetzen?', 'Rules + calc', 'Taxfix, WISO, Elster, native ChatGPT', 'Lead gen', 3, 4, 1, 5, 3, 3, 3, 1, 4, 1, 5, 45],
  ['kuendigung', 'Contract cancellation letter + deadline calc', 'Consumers', 'Finding notice periods, sending legally valid cancellation', 'Aboalarm, Volders', 'Kündige meinen Fitnessstudiovertrag', 'Deadline calc + letter + send fax/letter', 'Aboalarm, Volders, native ChatGPT letters', 'Per send 2-5 EUR', 3, 3, 2, 5, 3, 4, 3, 2, 3, 2, 5, 35],
  ['flight-comp', 'Flight delay compensation claim (EU261)', 'Travellers', 'Claiming 250-600 EUR is tedious', 'Flightright (20-30% fee)', 'Mein Flug hatte 4h Verspätung, steht mir Geld zu?', 'Flight status data + EU261 rules + claim letter', 'Flightright, AirHelp, native rules', 'Success fee or flat fee', 5, 2, 4, 4, 4, 4, 4, 2, 3, 2, 5, 40],
  ['bahn-refund', 'Deutsche Bahn Fahrgastrechte form', 'German rail travellers', 'Delay compensation forms', 'DB app form', 'Mein ICE war 70 Minuten zu spät', 'Rules + form filling', 'DB Navigator now native, Zugerstattung sites', 'Low', 2, 2, 3, 4, 3, 3, 3, 1, 4, 2, 4, 30],
  ['grant-finder', 'Förderprogramm finder (DE SMB grants)', 'German SMBs/founders', 'Hundreds of federal/state programs, hard to find eligibility', 'Berater, foerderdatenbank.de', 'Welche Förderung gibt es für eine Wärmepumpe in Bayern?', 'Structured Förderdatenbank + eligibility logic', 'foerderdatenbank.de, consultants, native search', 'Lead gen to consultants, B2B', 4, 4, 2, 5, 4, 4, 4, 3, 3, 2, 4, 30],
  ['energy-ausweis', 'Heating/energy subsidy calculator (BEG/GEG)', 'Homeowners', 'Heat pump subsidy rules complex', 'Energy consultant', 'Wieviel Förderung bekomme ich für eine Wärmepumpe?', 'Rule engine + current rates', 'Installer sites, consultants', 'Lead gen to installers', 4, 4, 1, 5, 4, 4, 4, 2, 4, 1, 5, 35],
  ['gdpr-dsar', 'DSGVO Auskunft request + tracker', 'Consumers', 'Requesting personal data from companies', 'Templates, datenanfragen.de', 'Ich will wissen welche Daten Firma X über mich hat', 'Company DPO address DB + letter', 'datenanfragen.de (free)', 'Low', 2, 3, 1, 4, 3, 4, 3, 1, 4, 2, 3, 25],
  ['impressum', 'Website legal check (Impressum/cookie/DSGVO)', 'Small website owners', 'Abmahnung risk', 'eRecht24 generator', 'Ist meine Website abmahnsicher?', 'Crawl site + rule checks', 'eRecht24, IT-Recht Kanzlei', 'Subscription', 4, 4, 2, 4, 4, 4, 4, 2, 3, 2, 4, 45],
  ['accessibility', 'BFSG/EAA website accessibility check', 'EU e-commerce SMBs (EAA since June 2025)', 'Legal accessibility obligation, audits expensive', 'Agencies, overlays', 'Ist mein Shop barrierefrei nach BFSG?', 'Automated axe-core audit + prioritized fixes', 'accessiBe, WAVE, agencies', 'Per scan / subscription', 4, 4, 3, 4, 4, 5, 4, 2, 3, 4, 3, 30],
  ['seo-audit', 'SEO page audit', 'Marketers', 'On-page audits', 'Ahrefs, Screaming Frog', 'Audit my homepage SEO', 'Crawl + SERP data', 'Semrush/Ahrefs apps already in ChatGPT', 'Subscription', 2, 3, 3, 4, 3, 4, 3, 1, 4, 3, 4, 15],
  ['amazon-listing', 'Amazon listing compliance/keyword check', 'Amazon sellers', 'Suppressed listings, keyword gaps', 'Helium10', 'Why is my listing suppressed?', 'Marketplace data', 'Helium10, Jungle Scout', 'Subscription', 4, 3, 4, 3, 3, 4, 3, 2, 3, 4, 3, 25],
  ['etsy-fees', 'Marketplace fee & margin calculator', 'Etsy/eBay/Amazon sellers', 'True margin after fees', 'Spreadsheets', 'What is my profit selling this on Etsy at 25 EUR?', 'Maintained fee tables', 'Free calculators', 'Free/affiliate', 2, 2, 4, 4, 3, 4, 2, 3, 5, 3, 3, 15],
  ['pdf-forms', 'Fill official PDF forms (AcroForm)', 'Anyone filling government forms', 'Retyping data into PDF forms', 'Adobe, print & write', 'Fill this Kindergeld form with my data', 'Real AcroForm filling, flatten', 'Adobe Acrobat (in ChatGPT), native partial', 'Per form', 3, 4, 3, 4, 3, 3, 3, 2, 4, 3, 3, 35],
  ['doc-compare', 'Contract version redline compare', 'Lawyers, procurement', 'Spotting changes between versions', 'Word compare, Draftable', 'What changed between v1 and v2 of this contract?', 'Exact diff engine + redline docx', 'Word compare, Draftable, native ChatGPT', 'Per doc / subscription', 3, 4, 3, 4, 3, 3, 4, 3, 4, 3, 3, 25],
  ['insurance-compare', 'Insurance policy comparison (DE Gewerbe)', 'SMBs, brokers', 'Comparing coverage tables across offers', 'Excel matrices', 'Compare these 3 liability offers', 'Coverage taxonomy + matrix', 'Broker software, native ChatGPT', 'B2B broker SaaS', 4, 4, 3, 4, 2, 2, 4, 3, 3, 3, 3, 35],
  ['rfq-compare', 'Supplier quote comparison', 'Procurement in SMBs', 'Normalizing 3-5 supplier quotes', 'Excel', 'Compare these supplier quotes and pick the best', 'Normalization + XLSX', 'Native ChatGPT data analysis strong', 'Subscription', 3, 3, 3, 4, 2, 2, 4, 3, 3, 3, 3, 30],
  ['meeting-minutes', 'Meeting minutes formatter', 'Office workers', 'Turning notes into minutes', 'Word', 'Turn these notes into minutes', 'None beyond prompting', 'Native ChatGPT, Copilot', 'None', 2, 2, 5, 1, 1, 1, 1, 5, 3, 2, 2, 60],
  ['email-reply', 'Email templating', 'Support agents', 'Repetitive replies', 'Templates', 'Draft a reply to this complaint', 'None beyond prompting', 'Native ChatGPT, Gmail apps', 'None', 2, 2, 5, 1, 2, 1, 1, 5, 4, 2, 2, 60],
  ['crm-update', 'CRM update from call notes', 'Sales reps', 'Logging calls in CRM', 'Manual entry', 'Log this call in HubSpot', 'Write action into CRM', 'HubSpot/Salesforce official apps in ChatGPT', 'Subscription', 2, 3, 5, 4, 5, 3, 1, 3, 4, 3, 3, 25],
  ['timesheet-invoice', 'Timesheet to invoice (freelancers)', 'Freelancers', 'Monthly invoicing from tracked hours', 'Toggl export + Word', 'Make an invoice from my October hours', 'Toggl/Clockify API + invoice PDF', 'Toggl, Harvest, accounting suites', 'Subscription', 4, 3, 4, 4, 4, 4, 3, 3, 3, 3, 3, 25],
  ['payment-reminder', 'Mahnwesen (dunning letters with interest calc)', 'Freelancers/SMBs', 'Late payers; legal interest (§288 BGB) calc', 'Templates', 'Kunde zahlt nicht, schreib eine Mahnung mit Zinsen', 'Exact base-rate interest calc + letter', 'Native ChatGPT letters, accounting suites', 'Per letter', 4, 3, 3, 4, 4, 3, 4, 3, 3, 3, 3, 30],
  ['leitweg', 'Public sector invoicing helper (Leitweg-ID, portals)', 'Suppliers to German authorities', 'Submitting XRechnung via ZRE/OZG-RE portals', 'Manual portal upload', 'Wie schicke ich eine Rechnung an die Stadt München?', 'Portal/Leitweg data + validation', 'Rechnungslotse, accounting suites', 'Per invoice', 4, 3, 2, 4, 4, 4, 4, 3, 3, 3, 2, 25],
  ['peppol-lookup', 'Peppol participant lookup', 'B2B finance teams (BE, DE)', 'Is customer on Peppol, what ID?', 'Peppol directory', 'Is customer X reachable via Peppol?', 'Peppol directory API', 'Peppol directory (free)', 'Low', 2, 2, 3, 3, 4, 5, 3, 1, 4, 2, 3, 15],
  ['company-lookup', 'Handelsregister/company check (KYB)', 'SMBs vetting partners', 'Checking company existence, directors', 'handelsregister.de, North Data', 'Ist die Firma XY GmbH seriös?', 'Register data + risk signals', 'North Data, Creditreform', 'Credits', 3, 3, 4, 4, 4, 4, 3, 2, 3, 3, 3, 35],
  ['trademark', 'Trademark availability pre-check (DPMA/EUIPO)', 'Founders', 'Naming risk', 'DPMAregister, lawyers', 'Kann ich den Namen X als Marke nutzen?', 'Register search APIs + class mapping', 'Lawyers, Trademarkia', 'Lead gen', 4, 4, 1, 5, 4, 3, 4, 3, 3, 1, 4, 40],
  ['recipe-macro', 'Recipe nutrition calculator', 'Fitness users', 'Macro counting', 'MyFitnessPal', 'Macros for this recipe?', 'Food DB', 'MyFitnessPal, native estimates', 'Freemium', 2, 2, 5, 3, 3, 4, 1, 4, 4, 3, 2, 15],
  ['real-estate-yield', 'Rental property yield calculator (DE)', 'Small investors', 'Mietrendite, Grunderwerbsteuer, AfA', 'Excel', 'Lohnt sich diese Wohnung für 280k mit 900 EUR Miete?', 'Exact DE tax/cost rules + local rent data', 'Excel, Immocation, native ChatGPT', 'Freemium', 3, 3, 2, 4, 3, 3, 3, 3, 3, 3, 4, 20],
  ['mietspiegel', 'Mietspiegel / Mietpreisbremse checker', 'German tenants', 'Is my rent legal under Mietpreisbremse?', 'Mieterverein, Conny', 'Ist meine Miete zu hoch?', 'Local Mietspiegel tables + calc', 'Conny (success fee), Mietpreisbremse calculators', 'Lead gen / success fee', 4, 5, 1, 5, 4, 4, 3, 3, 2, 1, 5, 40],
  ['kaution', 'Mietkaution return deadline/interest calc', 'Tenants after move-out', 'Getting deposit back with interest', 'Templates', 'Vermieter gibt meine Kaution nicht zurück', 'Interest calc + letter', 'Native ChatGPT letters', 'Per letter', 3, 3, 1, 4, 3, 3, 2, 3, 4, 1, 4, 35],
  ['payroll-minijob', 'Minijob/Midijob calculator & compliance', 'Small employers', 'Limits & contributions change yearly', 'Minijob-Zentrale', 'Kann ich jemanden für 600 EUR anstellen?', 'Current thresholds + calc', 'Minijob-Zentrale calculators', 'Low', 2, 3, 2, 4, 3, 4, 3, 2, 4, 2, 3, 25],
  ['hr-arbeitszeit', 'Working-time compliance check (ArbZG)', 'Small employers', 'Rota violations of rest periods', 'Excel rotas', 'Check this shift plan for ArbZG violations', 'Deterministic rule engine', 'Rota software', 'Subscription', 3, 3, 3, 4, 3, 4, 3, 3, 3, 4, 3, 25],
  ['csv-clean', 'Address list cleanup & dedupe', 'Office admins', 'Dirty contact lists', 'Excel', 'Clean and dedupe this address list', 'Postal validation data', 'Native ChatGPT data analysis', 'Low', 2, 3, 3, 4, 2, 3, 2, 2, 4, 2, 3, 30],
  ['iban-sepa', 'SEPA XML payment file generator', 'SMBs paying many suppliers', 'Bulk transfers need pain.001 XML', 'Banking software', 'Make a SEPA file for these 12 payments', 'Valid pain.001 output + IBAN checks', 'Banking software, StarMoney', 'Per file', 3, 3, 3, 3, 4, 3, 3, 3, 4, 3, 3, 30],
  ['ics-schedule', 'Exam/shift schedule to calendar', 'Students/workers', 'Turning PDFs into calendar events', 'Manual entry', 'Put this shift plan in my calendar', 'ICS output / calendar write', 'Native ChatGPT + Google Calendar app', 'Low', 2, 2, 4, 2, 4, 2, 2, 1, 4, 3, 3, 25],
  ['co2-split', 'CO2 cost split calculator (CO2KostAufG)', 'Landlords and tenants', 'Since 2023 CO2 heating cost must be split by building class', 'Online calculators', 'Wie viel CO2-Kosten muss mein Vermieter übernehmen?', 'Exact 10-step model calc', 'Free calculators', 'Feature of nk-check', 1, 3, 2, 3, 5, 4, 3, 3, 5, 2, 3, 20],
].map((r) => ({
  id: r[0], name: r[1], targetUser: r[2], problem: r[3], workaround: r[4], examplePrompt: r[5],
  pluginEdge: r[6], alternatives: r[7], monetization: r[8], mvpDays: r[9],
  scores: { pain: r[10], freq: r[11], fit: r[12], native: r[13], mcp: r[14], wtp: r[15], comp: r[16], mvp: r[17], ret: r[18], dist: r[19] },
  risk: r[20],
}));

export function opportunityScore(s) {
  let total = 0;
  for (const [k, w] of Object.entries(WEIGHTS)) total += (w * (s[k] - 1)) / 4;
  return Math.round(total);
}

// Expected value discounts the opportunity score by half the risk.
export function expectedValue(score, risk) {
  return Math.round(score * (1 - risk / 200));
}

export function ranked() {
  return ROWS.map((o) => {
    const score = opportunityScore(o.scores);
    return { ...o, score, ev: expectedValue(score, o.risk) };
  }).sort((a, b) => b.ev - a.ev);
}
